environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_ARCH: "64"

platform:
    -x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install -q numpy scipy matplotlib coverage setuptools h5py pandas pytest pytest-cov pytest-timeout codecov pyglet mne tdtpy joblib numpydoc pillow"
  - "python -c \"import mne; mne.sys_info()\""
  # Get a virtual sound card / VBAudioVACWDM device
  - "git clone --depth 1 git://github.com/LABSN/sound-ci-helpers.git"
  - "powershell sound-ci-helpers/windows/setup_sound.ps1"
  - "pip install rtmixer"
  - "python -m sounddevice"
  # OpenGL (should provide a Gallium driver)
  - "git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"
  - "python -c \"import pyglet; r = pyglet.gl.gl_info.get_renderer(); print(r); assert 'gallium' in r.lower()\""
  # expyfun
  - "powershell make/get_video.ps1"
  - "python setup.py develop"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Ensure that video works
  - "python -c \"import expyfun; assert expyfun._utils._has_video()\""
  # Run the project tests
  - "pytest --cov=expyfun expyfun"

on_success:
  - "codecov"
