environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"

platform:
    -x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET _EXPYFUN_SILENT=true"
  - "python --version"
  - "powershell make/get_avbin.ps1"
  - "pip install numpy scipy matplotlib coverage setuptools h5py pandas pytest pytest-cov codecov"
  - "pip install pyglet mne tdtpy"
  - "python setup.py develop"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Ensure that AVBin works
  - "python -c \"import expyfun; assert expyfun._utils._has_avbin()\""
  # Run the project tests
  - "pytest expyfun --cov=expyfun"

on_success:
  - "codecov"
