name: 'linux / conda'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  # Linux
  job:
    name: 'py3.9'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    env:
      DISPLAY: ':99.0'
      _EXPYFUN_SILENT: 'true'
    steps:
      - uses: actions/checkout@v2
      - run: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
      - run: sudo apt-get install libavutil56 libavcodec58 libavformat58 libglu1-mesa dbus-x11
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: 'test'
          python-version: '3.9'
          environment-file: 'environment_test.yml'
        name: 'Setup conda'
      - run: git clone --depth=1 git://github.com/LABSN/sound-ci-helpers.git && sound-ci-helpers/linux/setup_sound.sh
        name: Get sound working
      - run: python -m sounddevice
      - run: python -c "import pyglet; print(pyglet.version)"
      - run: python -c "import matplotlib.pyplot as plt"
      - run: python setup.py develop
      - run: python -c "import expyfun; expyfun._utils._has_video(raise_error=True)"
      - run: pytest --tb=short -n 1 --cov=expyfun expyfun
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Codecov'
