name: 'linux'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: pip ${{ matrix.python }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python: ['3.10']
    env:
      DISPLAY: ':99.0'
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - run: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
        name: Start Xvfb
      - run: sudo apt update -q && sudo apt install -q libavutil56 libavcodec58 libavformat58 libswscale5 libglu1-mesa gstreamer1.0-alsa gstreamer1.0-libav python3-gst-1.0
        name: Install system dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
        name: 'Setup python'
      - run: pip install --upgrade pip setuptools wheel
        name: Upgrade pip
      - run: pip install --upgrade sounddevice rtmixer "pyglet<1.6" pyglet_ffmpeg scipy matplotlib pandas h5py coverage mne numpydoc pytest pytest-cov pytest-timeout pillow joblib codecov
        name: Dependencies
      - run: git clone --depth=1 git://github.com/LABSN/sound-ci-helpers.git && sound-ci-helpers/auto.sh
        name: Get sound working
      - run: python -m sounddevice
        name: List sound devices
      - run: python -c "import pyglet; print(pyglet.version)"
        name: Print Pyglet version
      - run: python -c "import matplotlib.pyplot as plt"
        name: Make sure matplotlib works
      - run: pip install -ve .
        name: Install
      - run: python -c "import expyfun; expyfun._utils._has_video(raise_error=True)"
        name: Check video
      - run: pytest --tb=short --cov=expyfun --cov-report=xml expyfun
        name: Pytest
      - uses: codecov/codecov-action@v1
        if: success()
        name: Codecov
