name: 'macos'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: conda ${{ matrix.python }}
    runs-on: macos-latest
    strategy:
      matrix:
        python: ['3.10']
    defaults:
      run:
        shell: bash -el {0}
    env:
      PYTHON_VERSION: '3.10'
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: 'test'
          python-version: ${{ env.PYTHON_VERSION  }}
          environment-file: 'environment_test.yml'
        name: 'Setup conda'
      - run: pip install sounddevice rtmixer "pyglet<1.6"
      - run: git clone --depth=1 git://github.com/LABSN/sound-ci-helpers.git && sound-ci-helpers/auto.sh
        name: Get sound working
      - run: python -m sounddevice
      - run: python -c "import pyglet; print(pyglet.version)"
      - run: python -c "import matplotlib.pyplot as plt"
      - run: pip install -ve .
      - run: python -c "import expyfun; expyfun._utils._has_video(raise_error=True)"
      - run: pytest --tb=short --cov=expyfun --cov-report=xml expyfun
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Codecov'
