name: 'macos / conda'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: 'py3.9'
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: 'test'
          python-version: '3.9'
          environment-file: 'environment_test.yml'
        name: 'Setup conda'
      - run: git clone --depth=1 git://github.com/LABSN/sound-ci-helpers.git && brew install ffmpeg && sound-ci-helpers/macos/setup_sound.sh
        name: Get sound working
      - run: python -m sounddevice
      - run: python -c "import pyglet; print(pyglet.version)"
      - run: python -c "import matplotlib.pyplot as plt"
      - run: pip install -ve .
      - run: python -c "import expyfun; expyfun._utils._has_video(raise_error=True)"
      - run: pytest --tb=short -n 1 --cov=expyfun expyfun
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Codecov'
